### ISSUE TITLE
Removing files and folders

### ISSUE THREAD

**Issue by mejroslav** [Quacken8/MagneticDisconnectSimulator#5]
https://github.com/Quacken8/MagneticDisconnectSimulator/blob/faef3bd8e65fb5808206e7455553f4014a215acd/UnitTests.py#L25-L26

Isn't this dangerous? If not, you can use `os.rmdir()` method.

**Comment by Quacken8** [comment]
I don't believe it is becuse the unit test won't overwrite an existing folder with its temporary one and only removes the one it creates.

`os.rmdir()` for some reason doesn't support recursive deletion IIRC
