### ISSUE TITLE
`dataStructure.py` suggestions

### ISSUE THREAD

**Issue by mejroslav** [Quacken8/MagneticDisconnectSimulator#6]
https://github.com/Quacken8/MagneticDisconnectSimulator/blob/faef3bd8e65fb5808206e7455553f4014a215acd/dataStructure.py#L164-L174

Maybe you can create a new function?
```python
def saveToFile(filename, ... , data):
   header = f"temperature [{something}], rows index depth, columns index time"
   np.savetxt(filename, data.T, header=header, delimiter=",") 
```

**Comment by mejroslav** [comment]
https://github.com/Quacken8/MagneticDisconnectSimulator/blob/faef3bd8e65fb5808206e7455553f4014a215acd/dataStructure.py#L44-L60

Maybe you can simplify the attribute setting using `**kwargs` argument? I think something like this should work:
```python
class MyClass:
    def __init__(self, **kwargs):
        for key, value in kwargs.items():
            setattr(self, key, value)

# Example usage
my_instance = MyClass(temperature=25, density=1.2, pressure=100)
```

**Comment by Quacken8** [comment]
> https://github.com/Quacken8/MagneticDisconnectSimulator/blob/faef3bd8e65fb5808206e7455553f4014a215acd/dataStructure.py#L164-L174
> 
> Maybe you can create a new function?
> 

Yes, a function for the saving will surely help readibility. Will do!

**Comment by Quacken8** [comment]
> https://github.com/Quacken8/MagneticDisconnectSimulator/blob/faef3bd8e65fb5808206e7455553f4014a215acd/dataStructure.py#L44-L60
> 
> Maybe you can simplify the attribute setting using `**kwargs` argument? I think something like this should work:
> 
> ```python
> class MyClass:
>     def __init__(self, **kwargs):
>         for key, value in kwargs.items():
>             setattr(self, key, value)
> 
> # Example usage
> my_instance = MyClass(temperature=25, density=1.2, pressure=100)
> ```

I'm not super sure about this one, becuase it is necessary that all the variables are given to the constructor. I'd still have to check for all of the keys having values, but I guess it would shorten the code a bit...
